#!/bin/bash

echo "Checking for changes in web/src..."
if git diff --name-only @{push}...HEAD | grep -q 'web/src'; then
  echo "Changes detected in web/src since the last push. Running npm run build to ensure the project builds successfully..."
  echo "Linting files..."
  cd web
  if npx lint-staged; then
    echo "Linting files... Done"
  else
    echo "Linting failed. Please fix the errors and try again."
    exit 1
  fi
else
  echo "No changes detected in web/src since the last push. Skipping build..."
fi
