#!/bin/bash

echo "Checking for changes in web/src..."
if git diff --quiet HEAD web/src; then
  echo "No changes in web/src"
else
  echo "Linting files..."
  cd web
  if npx lint-staged; then
    echo "Linting files... Done"
  else
    echo "Linting failed. Please fix the errors and try again."
    exit 1
  fi
fi
